<a href="https://colab.research.google.com/github/Tclack88/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
Array input which is analogous to the independent variables of a function
### Hidden Layer:
If it's neither the input nor the prediction nodes, it's apart of the hidden layer. The hidden layer contains nodes which hold the output of either the input layer or a previous hidden layer (depending on the depth of the neural net)
### Output Layer:
The final set of nodes in a neural network. It contains the final output of the neural network
### Neuron:
A node in the neural network which contains just a single value. These values come from the previous neurons if in the hidden later or output layer based on weights and biases. If these neurons are in the input layer, they are just the starting values
### Weight:
a number, unique between each neuron-to-neuron connection, which determines how much of the input neuron's value will pass on to the next
### Activation Function:
The output of this is actually what determines the value of each neuron (based on the weights and biases. A good choice is something which takes any values on the input but whose output is restricted to between 0 and 1 such as a sigmoid (from tanh or logistic function) or a simply step function (this is not a hard rule though as with a relu function)
### Node Map:
A mnemonic used to visualize how the neural network is arranged
### Perceptron:
A specific and simple neural network consisting of two neurons in the input layer and one neuron in the output layer (no hidden layers exist)


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import numpy as np

In [3]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [0]:
def sigmoid(x):
  return 1 / (1 - np.exp(-x))
    
def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx * (1 - sx)


In [0]:
# initialize random weights, assume bias is 0 for simplicity
weights = 2*np.random.random((2,1)) - 1
# weights = np.zeros((2,1),dtype=float)
X = df[['x1','x2']].to_numpy()
y = df[['y']]

In [38]:

for _ in range(1000):
  output = np.dot(X, weights)
  error = y - output
  adjusted = error * sigmoid_derivative(output)
  weights += np.dot(X.T, adjusted)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [39]:
weights

array([[nan],
       [nan]])

### IGNORE BELOW UNTIL THE PERCEPTROPN IN PART II

In [0]:
# def sigmoid(x):
#   return 1/(1+np.exp(-x))
def error(pred, correct):
  return np.sum(np.square(correct - pred))

def gradient(pred, correct):
  """ based on derivative of:
  (c1 - p1)^2 + (c2 - p2)^2 + ... + (cn - pn)^2
  """
  return 2 * (correct - pred)

In [19]:
df[['x1','x2']].to_numpy()

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [30]:
input = df[['x1','x2']].to_numpy()
correct = df.y.to_numpy()

weights = 2*np.random.random((2,1)) - 1 # initialize with 2 random values
# weights = np.array([[2,0]])
# err = 1 
# while err > .01:

for _ in range(1000):
  pred = np.matmul(input,weights.T)
  err = error(pred, correct)
# np.matmul(input, weights)

array([[ 0.        ],
       [ 0.03517442],
       [-0.02219107],
       [ 0.01298334]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [40]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

scaler = MinMaxScaler()
X = scaler.fit_transform(diabetes[feats])
X = np.hstack((X, np.ones((diabetes.shape[0],1))))
y = diabetes[['Outcome']]

In [0]:
def sigmoid(x):
  return 1 / (1 - np.exp(-x))
    
def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx * (1 - sx)

##### Update this Class #####

class Perceptron(object):
    
  def __init__(self, niter = 10):
    self.niter = niter
    
  # def __sigmoid(self, x):
  #   return 1 / (1 - np.exp(-x))
    
  # def __sigmoid_derivative(self, x):
  #   self.x = x
  #   sx = self.__sigmoid(x)
  #   return sx * (1 - sx)

  def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

  # Randomly Initialize Weights
    # self.weights = np.zeros((X.shape[1],1))
    self.weights = np.random.random((np.shape(X)[1],1))

    for i in range(self.niter):
      # Activate!
      output = sigmoid(np.dot(X,self.weights))
      # Cac error
      error = y - output
      adjusted = error * sigmoid_derivative(output)
      # Update the Weights
      self.weights += np.dot(X.T, adjusted)
      # Weighted sum of inputs / weights

  def predict(self, X):
    """Return class label after unit step"""
    return sigmoid(np.dot(X, self.weights))

In [0]:
perceptron = Perceptron(niter=10000)
perceptron.fit(X,y)

In [0]:
pred = perceptron.predict(X)

In [48]:
from sklearn.metrics import accuracy_score

accuracy_score(pred,y)

0.3489583333333333

:[

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?