<a href="https://colab.research.google.com/github/Tclack88/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module2-backpropagation/LS_DS_422_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
import pandas as pd
import numpy as np

In [3]:
data = {'x1': [0,0,1,0,1,1,0],
        'x2': [0,1,0,1,0,1,0],
        'x3': [1,1,1,0,0,1,0],
        'y': [0,1,1,1,1,0,0]}
df = pd.DataFrame(data)
df

x1  x2  x3  y
0   0   0   1  0
1   0   1   1  1
2   1   0   1  1
3   0   1   0  1
4   1   0   0  1
5   1   1   1  0
6   0   0   0  0

In [0]:
X = df[['x1','x2','x3']]
y = df[['y']]

In [32]:
y

y
0  0
1  1
2  1
3  1
4  1
5  0
6  0

In [0]:
class NeuralNetwork(object):
  def __init__(self):
    """initialize neural network architecture"""
    self.input_layer = 3
    self.hidden_layer = 3
    self.output_layer = 1
  
    # initialize with (small positive) random weights with appropriate sizes
    self.weights1 = np.random.rand(self.input_layer, self.hidden_layer)
    self.weights2 = np.random.rand(self.hidden_layer, self.output_layer)

  def sigmoid(self,x):
    return 1 / (1 + np.exp(-x))

  def sigmoid_derivative(self, s):
    return s * (1 - s)

  def feed_forward(self, X):
    """ make predictions from given weights """

    self.hidden_sum = np.dot(X, self.weights1)
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    self.activated_output = self.sigmoid(self.output_sum)
    return self.activated_output

  def back_propogation(self, X, y, o):
    """ back propogation to adjust the weights in the neural network """
    self.output_error = y - o
    self.output_adjustments = self.output_error * self.sigmoid_derivative(o)
    self.hidden_error = np.dot(self.output_adjustments, self.weights2.T)# transpose because we are "going backwards" in the neural net, so the dimensions need to match up
    self.hidden_adjustments = self.hidden_error * self.sigmoid_derivative(self.activated_hidden)

    # adjust weights
    self.weights1 += np.dot(X.T, self.hidden_adjustments)
    self.weights2 += np.dot(self.activated_hidden.T, self.output_adjustments)

  def train(self, X, y):
    o = self.feed_forward(X)
    self.back_propogation(X, y, o)


In [0]:
nn = NeuralNetwork()

In [54]:
# NOTE: Code below taken directly from lecure for simplicity
# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
    x1  x2  x3
0   0   0   1
1   0   1   1
2   1   0   1
3   0   1   0
4   1   0   0
5   1   1   1
6   0   0   0
Actual Output: 
    y
0  0
1  1
2  1
3  1
4  1
5  0
6  0
Predicted Output: 
 [[0.58657116]
 [0.60083137]
 [0.60151926]
 [0.58866811]
 [0.58783966]
 [0.61390143]
 [0.57140601]]
Loss: 
 y    0.24352
dtype: float64
+---------EPOCH 2---------+
Input: 
    x1  x2  x3
0   0   0   1
1   0   1   1
2   1   0   1
3   0   1   0
4   1   0   0
5   1   1   1
6   0   0   0
Actual Output: 
    y
0  0
1  1
2  1
3  1
4  1
5  0
6  0
Predicted Output: 
 [[0.58043917]
 [0.59388403]
 [0.59461018]
 [0.58271317]
 [0.58206423]
 [0.60627045]
 [0.56653318]]
Loss: 
 y    0.243358
dtype: float64
+---------EPOCH 3---------+
Input: 
    x1  x2  x3
0   0   0   1
1   0   1   1
2   1   0   1
3   0   1   0
4   1   0   0
5   1   1   1
6   0   0   0
Actual Output: 
    y
0  0
1  1
2  1
3  1
4  1
5  0
6  0
Predicted Output: 
 [[0.57756656]
 [0.59076727]
 [0.59142086]
 [0.58013

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [4]:
# removing tf2 behavior as per the warning that tf2 will be imported soon into colab
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [6]:
tf.__version__

'1.15.0'

In [0]:
# input image dimensions
img_rows, img_cols = 28, 28

In [0]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [10]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [0]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [22]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

In [0]:
# Get random indices for grabbing training smaples
sample_index = np.random.randint(x_train.shape[0],size=500)
X_sample = x_train[sample_index]
y_sample = y_train[sample_index]

### Estimating Your `net

In [0]:
class NeuralNetwork(object):
  def __init__(self):
    """initialize neural network architecture"""
    self.input_layer = 784 # 28 x 28, the size of our 
    self.hidden_layer1 = 16
    self.hidden_layer2 = 16
    self.output_layer = 1
  
    # initialize with (small positive) random weights with appropriate sizes
    self.weights1 = np.random.rand(self.input_layer, self.hidden_layer1)
    self.weights2 = np.random.rand(self.hidden_layer1, self.hidden_layer2)
    self.weights3 = np.random.rand(self.hidden_layer2, self.output_layer)

  def sigmoid(self,x):
    return 1 / (1 + np.exp(-x))

  def sigmoid_derivative(self, s):
    return s * (1 - s)

  def feed_forward(self, X):
    """ make predictions from given weights """

    self.hidden1_sum = np.dot(X, self.weights1)
    self.activated_hidden1 = self.sigmoid(self.hidden1_sum)
    self.hidden2_sum = np.dot(self.activated_hidden1, self.weights2)
    self.activated_hidden2 = self.sigmoid(self.hidden2_sum)
    self.output_sum = np.dot(self.activated_hidden2, self.weights3)
    self.activated_output = self.sigmoid(self.output_sum)
    return self.activated_output

  def back_propogation(self, X, y, o):
    """ back propogation to adjust the weights in the neural network """
    self.output_error = y - o
    self.output_adjustments = self.output_error * self.sigmoid_derivative(o)
    self.hidden2_error = np.dot(self.output_adjustments, self.weights3.T)# transpose because we are "going backwards" in the neural net, so the dimensions need to match up
    self.hidden2_adjustments = self.hidden2_error * self.sigmoid_derivative(self.activated_hidden2)
    self.hidden1_error = np.dot(self.hidden2_adjustments, self.weights2.T)
    self.hidden1_adjustments = self.hidden1_error * sigmoid_derivative(activated_hidden1)

    # adjust weights
    self.weights1 += np.dot(X.T, self.hidden1_adjustments)
    self.weights2 += np.dot(self.activated_hidden1.T, self.hidden2_adjustments)
    self.weights3 += np.dot(self.activated_hidden2.T, self.output_adjustments)

  def train(self, X, y, n_iter=10):
    for epoch in range(n_iter):
      o = self.feed_forward(X)
      self.back_propogation(X, y, o)

  def predict(self, X):
    return np.array([ 1 if prediction >= .5 else 0 for prediction in self.feed_forward(X)])


In [27]:
nn = NeuralNetwork()
nn.train(X_sample,y_sample)

ValueError: ignored

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?